### ISSUE TITLE
Add option to specify an aws credentials file

### ISSUE THREAD

**Issue by aceew** [SamVerschueren/aws-swagger-import#7]
Could we get the ability to specify a filename for AWS.SharedIniFileCredentials instead of using the default parameter value '~/.aws/credentials'. See https://github.com/SamVerschueren/aws-swagger-import/blob/master/lib/apigateway.js#L17

From the aws documentation. http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html

```
Constructor Details

new AWS.SharedIniFileCredentials(options) ⇒ void

Creates a new SharedIniFileCredentials object.

Parameters:
options (map) — a set of options
Options Hash (options):
profile (String) — default: AWS_PROFILE env var or 'default' — the name of the profile to load.
filename (String) — default: '~/.aws/credentials' — the filename to use when loading credentials.
```

**Comment by SamVerschueren** [comment]
Good suggestion!

---

Just a little note off topic. 
This library is far from complete and is likely to have various bugs in it. So although I find it very pleasant that is used by other people, I just want them to know it's really a work in progress library created because the "official" importer wasn't really user friendly to setup imo. But, just so you know :).

**Comment by aceew** [comment]
Hi @SamVerschueren,
Thanks for the reply. I agree, the official importer is a pretty nasty solution for the project I'm using this in.  I'd be happy to contribute if you are accepting pull requests from other people.

**Comment by SamVerschueren** [comment]
Absolutely! PR`s are more then welcome :)
